# HEADER INFORMATION
name: name
wd: C:\Users\Paul.Stevenson\
frequency: one-time
load_time: 00:01

# DESCRIPTION
description: ELT Framework Dev Project

# PIPLELINE STEPS
steps:
  - name: extract_data
    type: extract_etl
    path: x
    output: etl.RDS
    code: 23-import_sas_dataset.R

  - name: import_randomisation
    type: extract_xls
    input: x
    output: rand.RDS
    code: 21-import_xls.R

  - name: import_analysis_sets
    type: extract_xls
    input: x
    output: sets.RDS
    code: 21-import_xls.R

  - name: prepare_study_data
    type: transform_data
    input:
      - dat: etl.RDS
      - rand: rand.RDS
      - sets: sets.RDS
    output: dat.RData
    code: 01-munge.R

  - type: listing_data
    number:
      - L_16_02_01_01
      - L_16_02_01_02

  - type: table_data
    number:
      - T_14_01_01
